# name: Deploy Frontend
# on:
#   push:
#     branches:
#       - main # check your repo, your default branch might be master!
 
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#       - run: docker build -t sairahul3/react-test -f Dockerfile.dev .
#       - run: docker run -e CI=true sairahul3/react-test npm test
 
#       - name: Generate deployment package
#         run: zip -r deploy.zip . -x '*.git*'
 
#       - name: Deploy to EB
#         uses: einaregilsson/beanstalk-deploy@v21
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#           application_name: DockerApp
#           environment_name: DockerApp-env
#           existing_bucket_name: elasticbeanstalk-ap-south-1-736087277987
#           region: ap-south-1
#           version_label: ${{ github.sha }}
#           deployment_package: deploy.zip

name: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master
      
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    
      - name: Generate deployment package
        run: zip -r deploy.zip frontend -x "**node_modules**"
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: DockerApp
          environment_name: DockerApp-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-736087277987
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip